### ISSUE TITLE
Segmentation & polygon button failure.

### ISSUE THREAD

**Issue by imunro** [flimfit/FLIMfit#112]
As reported by G.Chennell on Win7 Professional & Built version.

"I’m using flimfit 4.7.2 and have got a bug for you.
When segmenting multiple images using the polygon selection if the polygon button is depressed and I then switch to another image it is no longer possible to continue segmenting. The button will then not depress and no crosshairs will come up when hovering over the image for any of the selection shape options. The eraser button will still depress, if that is any help. 

It seems to only happen while the button is depressed while switching images.

Restarting the manager itself without closing the whole software lets me try again.

**Comment by seanwarren** [comment]
Should be resolved in v5
