### ISSUE TITLE
IRFs not loading in 4.12.1

### ISSUE THREAD

**Issue by Powerfultool** [flimfit/FLIMfit#292]
On loading an IRF in 4.12.1, no IRF is shown in the decay window - not yet sure if this is a loading or a display issue though. Same commands work fine in 4.12.0

**Comment by imunro** [comment]
I have reproduced this with the irf files in question but it is specific to some files not a general problem - thankfully.

**Comment by imunro** [comment]
As above, the issue turned out to be that I had been overcautious! I was treating it as an error if the user attempted to mix bio-formats compatible files with other types. Unfortunately this is exactly what you need to do.

**Comment by imunro** [comment]
@Powerfultool I'll e-mail a link for you to try the fix.
