### ISSUE TITLE
Please include LAPACK dependency

### ISSUE THREAD

**Issue by lacan** [flimfit/FLIMfit#293]
LAPACK seems to be required but is not written down in your dependency list.

**Comment by imunro** [comment]
Apologies for that.

**Comment by seanwarren** [comment]
@lacan thanks for the feedback, however LAPACK is an optional dependency of one of the fitting routines. FLIMfit should compile (and run) fine without it. The CMake flag HAS_LAPACK should be set automatically if LAPACK is detected. Please let me know if this isn't working for you

**Comment by imunro** [comment]
@iacan Can I ask if you are building FLIMfit for Linux? If so it would be great to have a PR for any changes required.
