### ISSUE TITLE
Old version Flags!

### ISSUE THREAD

**Issue by imunro** [flimfit/FLIMfit#294]
At https://github.com/flimfit/FLIMfit/blob/89e4e7869954d77f197c8895a68d725afb7c4855/BuildMacApp.sh#L2-L3     these flags are both out of date. 

Need to check if they are overidden in the build and if so remove.

Lokks as if they are overidden as the Build log gives:

BIO=5.2
PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
MATLAB_VER=R2016b
BOOST_VER_MINOR=59
BOOST_VER_MAJOR=1
OME=5.2   

 Although BIO & OME should probably be updated to 5.3

**Comment by seanwarren** [comment]
Hi Ian, BuildMacApp.sh is redundant and should be removed, I'll do this soon.

**Comment by imunro** [comment]
@seanwarren I just tried to modify the latest-mac build to use the current versions for BIO (5.4) & OME  (5.2) but I don't seem to be able to check the config at ci.flimfit.org.

**Comment by seanwarren** [comment]
Removed file in 93943f705af1a4a7a262375e58c2f381a5ab5e6c
