### ISSUE TITLE
Classpath issue in V5

### ISSUE THREAD

**Issue by imunro** [flimfit/FLIMfit#295]
On opening the latest_mac build I see the following:

Warning: "/Users/imunro/Library/Application Support/.mcrCache9.1/FLIMfi0/OMEuiUtils/OMEuiUtils.jar" is already specified on static java path.
> In javaclasspath>local_validate_dynamic_path
  In javaclasspath>local_javapath
  In javaclasspath
  In javaaddpath (line 71)
  In flim_fit_ui (line 191)
  In FLIMfit (line 39)
Warning: "/Users/imunro/Library/Application Support/.mcrCache9.1/FLIMfi0/OMEROMatlab/libs/ini4j.jar" is already specified on static java path.

@seanwarren have you changed the class path handling anywhere? 
We may be able to solve this by simply dropping the whole OMERO interface but that depends on funding.

**Comment by seanwarren** [comment]
Hi Ian, I haven't (intentionally) changed anything here, does this break anything or is it just a warning?

**Comment by imunro** [comment]
Just a warning. I just like to know why I'm getting then though :-)
________________________________

**Comment by seanwarren** [comment]
Should be resolved by 45da29ad4f6673b6f0e879aa6fa4655a209c3d3e
