### ISSUE TITLE
Error when aborting FLIMReader "Loading Options"

### ISSUE THREAD

**Issue by imunro** [flimfit/FLIMfit#298]
If I attempt to abort this window I get:

Error using matlab.ui.control.UIControl/get
Invalid or deleted object.
Error in FLIMreader_options_dialog/getNumberFromPopup (line 169)
Error in FLIMreader_options_dialog (line 146)
Error in flim_data_series/get_image_dimensions (line 259)
Error in flim_data_series/load_multiple (line 30)
Error in flim_data_series/load_single (line 104)
Error in flim_data_series_controller/load_single (line 167)
Error in front_end_menu_controller/menu_file_load_single_callback (line 654)
Error in front_end_menu_controller>@(varargin)obj.menu_file_load_single_callback(varargin{:})
Error in escaped_callback (line 7)
Error in front_end_menu_controller>@(x,y)escaped_callback(fcn) (line 261)

**Comment by seanwarren** [comment]
Resolved in 950bcef680444867f01c85452f12513d53f1978b - prevent manual abort of window
