### ISSUE TITLE
Lavision file format not recognized

### ISSUE THREAD

**Issue by VolkerSiffrin** [flimfit/FLIMfit#309]
13-24-06_1mM Glutamate_DC-TCSPC_C00_xyz-Table Z0000_TriMScope Axis0001_Time Time0009.ome.tif

**Comment by imunro** [comment]
Hi Volker. The issue , from our POV, is that Lavision use a very old version of the ome.tif standard, one that doesn't support FLIM. FLIMfit attempts to handle this but this may be a variant on there file-format that we haven't seen before. Can I ask you, as a first step, to upload a sample file to http://qa.openmicroscopy.org.uk/  (please fill in your e-mail in the feedback tab). Many thanks.  Ian

**Comment by sbesson** [comment]
Note that if the file is small enough and can be shared publicly, another alternative would be to upload it directly into this GitHub issue as it might simplify the discussion & interaction between the OME and FLIMfit teams.

**Comment by imunro** [comment]
That would certainly work for us. Thanks @sbesson

**Comment by imunro** [comment]
I'm afraid there's little we can do to address this in the absence of any test data, so closing this for the current release.
