### ISSUE TITLE
.sdt load-irf issue (5.0.2 - pre-release testing )

### ISSUE THREAD

**Issue by imunro** [flimfit/FLIMfit#310]
On loading a image from a .sdt file using IRF->Load IRF I see:
OSX 10.11.6
In the Error Report box:

Error using gmdistribution.fit (line 98)
Ill-conditioned covariance error occurred in every replicate.
Error in fitgmdist (line 130)
Error in flim_data_series/estimate_irf_background (line 44)
Error in flim_data_series/load_irf (line 128)
Error in front_end_menu_controller/menu_irf_load_callback (line 960)
Error in front_end_menu_controller>@(varargin)obj.menu_irf_load_callback(varargin{:})
Error in escaped_callback (line 7)
Error in front_end_menu_controller>@(x,y)escaped_callback(fcn) (line 261)

and in the text window

2017-05-07 13:35:24.213 FLIMfit[9190:58645] Failed to connect (typePopUp) outlet from (NSViewController) to (NSPopUpButton): missing setter or instance variable
Warning: Terminating replicate 3 for gmdistribution with 2 components. 
> In gmcluster (line 223)
  In gmdistribution.fit (line 98)
  In fitgmdist (line 130)
  In flim_data_series/estimate_irf_background (line 44)
  In flim_data_series/load_irf (line 128)
  In front_end_menu_controller/menu_irf_load_callback (line 960)
  In front_end_menu_controller>@(varargin)obj.menu_irf_load_callback(varargin{:})
  In escaped_callback (line 7)
  In front_end_menu_controller>@(x,y)escaped_callback(fcn) (line 261)
  In flim_fit_ui (line 218)
  In FLIMfit (line 39)
Warning: Terminating replicate 4 for gmdistribution with 2 components. 
> In gmcluster (line 223)
  In gmdistribution.fit (line 98)
  In fitgmdist (line 130)
  In flim_data_series/estimate_irf_background (line 44)
  In flim_data_series/load_irf (line 128)
  In front_end_menu_controller/menu_irf_load_callback (line 960)
  In front_end_menu_controller>@(varargin)obj.menu_irf_load_callback(varargin{:})
  In escaped_callback (line 7)
  In front_end_menu_controller>@(x,y)escaped_callback(fcn) (line 261)
  In flim_fit_ui (line 218)
  In FLIMfit (line 39)
Warning: Terminating replicate 7 for gmdistribution with 2 components. 
> In gmcluster (line 223)
  In gmdistribution.fit (line 98)
  In fitgmdist (line 130)
  In flim_data_series/estimate_irf_background (line 44)
  In flim_data_series/load_irf (line 128)
  In front_end_menu_controller/menu_irf_load_callback (line 960)
  In front_end_menu_controller>@(varargin)obj.menu_irf_load_callback(varargin{:})
  In escaped_callback (line 7)
  In front_end_menu_controller>@(x,y)escaped_callback(fcn) (line 261)
  In flim_fit_ui (line 218)
  In FLIMfit (line 39)
Warning: Terminating replicate 8 for gmdistribution with 2 components. 
> In gmcluster (line 223)
  In gmdistribution.fit (line 98)
  In fitgmdist (line 130)
  In flim_data_series/estimate_irf_background (line 44)
  In flim_data_series/load_irf (line 128)
  In front_end_menu_controller/menu_irf_load_callback (line 960)
  In front_end_menu_controller>@(varargin)obj.menu_irf_load_callback(varargin{:})
  In escaped_callback (line 7)
  In front_end_menu_controller>@(x,y)escaped_callback(fcn) (line 261)
  In flim_fit_ui (line 218)
  In FLIMfit (line 39)

**Comment by seanwarren** [comment]
@imunro, this is a problem with the irf background estimation when there is a very low background. I've finally got around to improving the method it uses, perhaps you could give it a bit of a try if possible? Particularly with some time gated data if possible . Cheers, Sean

**Comment by imunro** [comment]
Will do. Sorry, didn't have a chance to investigate yesterday but I'm back in the office today.

**Comment by imunro** [comment]
I re-ran the mac_release to include your fix but I still see the same error with .sdt images. OTOH it seems to be fine running from source. No errors are visible with gated data. If you need test data just let me know.

**Comment by imunro** [comment]
Looks like it's fixed!
