### ISSUE TITLE
Unable to load synthetic float ome-tiff (5.0.2 Pre-release Testing)

### ISSUE THREAD

**Issue by imunro** [flimfit/FLIMfit#313]
I just tried loading a synthetic ome-tiff generated using the code attached.
and got the following error! (see private e-mail from R.Laine)
[testOMETIFFGenerate.m.zip](https://github.com/flimfit/FLIMfit/files/989670/testOMETIFFGenerate.m.zip)

Undefined function or variable 'float'.
Error in flim_data_series/get_image_dimensions (line 63)
Error in flim_data_series/load_multiple (line 30)
Error in flim_data_series/load_single (line 104)
Error in flim_data_series_controller/load_single (line 167)
Error in front_end_menu_controller/menu_file_load_single_callback (line 654)
Error in front_end_menu_controller>@(varargin)obj.menu_file_load_single_callback(varargin{:})
Error in escaped_callback (line 7)
Error in front_end_menu_controller>@(x,y)escaped_callback(fcn) (line 261)

**Comment by seanwarren** [comment]
Cheers Ian, should be fixed by the latest commit

**Comment by imunro** [comment]
Now I get an error in load selected files at line 110 .
obj.data_series_mem = zeros([mem_size' num_sel],obj.data_type);

where obj.data_type is 'float'  & should I think be 'single'
Matlab supports:   Data Types: double | single | logical | int8 | int16 | int32 | int64 | uint8 | uint16 | uint32 | uint64

**Comment by imunro** [comment]
@seanwarren I just pushed this change. Can you check when you get a chance please.

**Comment by imunro** [comment]
I just pushed a matching change to the OMERO side to keep uint16 & 32 as that.

**Comment by imunro** [comment]
@seanwarren I'm still slightly concerned by "float' in the line I link above. I can't find where this is caught (& presumably changed to 'single' anyway)  before it creates the data.
