### ISSUE TITLE
Indistinguishable icons in OSX dock. (5.0.2 Pre-release testing)

### ISSUE THREAD

**Issue by imunro** [flimfit/FLIMfit#320]
FLIMfit on OSX creates 2 items in the dock while running (one for the GUI and another for the test o/p window) hitherto these have been distinguished by colour. The text one was B/W as opposed to blue & green. While v. minor this feature does enhance the user experience considerably. 
Could we do something similar in 5.0.2?

**Comment by imunro** [comment]
Actually I've just realised that they still are distinguished by colour - it's just v. subtle Dark Blue lines vs black.

**Comment by seanwarren** [comment]
@imunro, I'll make the difference a bit more obvious.

**Comment by imunro** [comment]
Thanks @seanwarren Not a blocker for 5.0.2 just nice to have.

**Comment by seanwarren** [comment]
Fixed
