### ISSUE TITLE
LLVM crash on OSX

### ISSUE THREAD

**Issue by imunro** [flimfit/FLIMfit#331]
I just pulled these changes https://github.com/flimfit/FLIMfit/commit/7a27d26413729a08564e10d5a349ed1ed07ff57e
into the LaVision branch. I then started to see the errors below on any attempt to fit.
Confirmed using the latest-mac build.

The error mentions 2 versions of OMP. Possible clash with the OMP used by Matlab.

OMP: Error #15: Initializing libomp.dylib, but found libiomp5.dylib already initialized.
OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
------------------------------------------------------------------------
              abort() detected at Mon Aug  7 14:34:56 2017
------------------------------------------------------------------------
Configuration:
  Crash Decoding      : Disabled - No sandbox or build area path
  Crash Mode          : continue (default)
  Current Graphics Driver: Intel Inc. Intel Iris OpenGL Engine Version 2.1 INTEL-10.14.73
  Current Visual      : Quartz
  Default Encoding    : ISO-8859-1
  Deployed            : true
  Host Name           : dyn1195-38.wlan.ic.ac.uk
  MATLAB Architecture : maci64
  MATLAB Entitlement ID: Unknown
  MATLAB Root         : /Applications/MATLAB/MATLAB_Runtime/v91
  MATLAB Version      : 9.1.0.441655 (R2016b)
  OpenGL              : hardware
  Operating System    : Darwin 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64
  Processor ID        : x86 Family 6 Model 69 Stepping 1, GenuineIntel
  Virtual Machine     : Java 1.7.0_75-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System       : Quartz
Fault Count: 1
Abnormal termination:
abort()
Register State (from fault):
  RAX = 0000000000000001  RBX = 0000000000000000
  RCX = 0000000000000003  RDX = 0000700000d2c35c
  RSP = 0000000000000016  RBP = 00007fff8e18b2ff

**Comment by imunro** [comment]
On further investigation this one must have been there since the LLVM change and must therefore be data-specific.

**Comment by seanwarren** [comment]
Reverted to gcc
