### ISSUE TITLE
Fit instability when making small changes to reference lifetime in 5.0.3-33-ga3095b8e

### ISSUE THREAD

**Issue by Powerfultool** [flimfit/FLIMfit#341]
Hi all,

I've been trying to fit some dye data in 5.0.3-33-ga3095b8e, and when using a reference reconvolution, I found that if I typo'd the reference lifetime value, a shift of ~10ps results in a big change in the resulting fit - it goes to a bimodal distribution from a single one, and one of the shifts is a few hundred ps... This doesn't seem to happen in 4.12, so I'm guessing there's a potential bug somewhere?

-Sunil

**Comment by seanwarren** [comment]
Hi Sunil, 

Thanks for the report. Could you send me a dataset and reference data where you're observing this issue?

Cheers
Sean

**Comment by seanwarren** [comment]
Fixed in PR #345
