### ISSUE TITLE
FLIMfitFrontEnd

### ISSUE THREAD

**Issue by AndreZeug** [flimfit/FLIMfit#349]
updating bfopen, OMERO, etc. cauese timeout error (behind proxy) in websave.m
Error using websave (line 98)
The connection to URL 'http://downloads.openmicroscopy.org/bio-formats/5.8.2/artifacts/bfmatlab.zip' timed out after 5 seconds. Set options.Timeout to a higher value.

I did set manually to 
options.Timeout = 500;
using breakpoint in line 98 to make it work

**Comment by seanwarren** [comment]
Thanks for the report Andre, I've now extended the timeout for the downloads.
