### ISSUE TITLE
Cannot load .sdt files

### ISSUE THREAD

**Issue by pjmattei** [flimfit/FLIMfit#352]
Hello,

I am trying to use FLIMfit 5.1.1, but when attempting to load my data, the below message appears. I believe my configuration (MacOS HighSierra, 64bits, Matlab R2016b, java 1.8.0_191(jdk and jre updated)) may be responsible, since the same error occurs with other FLIMfit versions.

Thank you,

PJ

Error using flim_data_series/load_flim_cube (line 214)
Java exception occurred: 
java.lang.NegativeArraySizeException
	at loci.formats.in.SDTReader.openBytes(SDTReader.java:204)
	at loci.formats.ImageReader.openBytes(ImageReader.java:460)
	at loci.formats.ChannelFiller.openBytes(ChannelFiller.java:156)
	at loci.formats.ChannelSeparator.openBytes(ChannelSeparator.java:227)
	at loci.formats.ChannelSeparator.openBytes(ChannelSeparator.java:159)
	at loci.formats.ChannelSeparator.openBytes(ChannelSeparator.java:141)

Error in flim_data_series/load_selected_files (line 124)
Error in flim_data_series/load_multiple (line 116)
Error in flim_data_series/load_single (line 104)
Error in flim_data_series_controller/load_single (line 168)
Error in front_end_menu_controller/menu_file_load_single_callback (line 656)
Error in front_end_menu_controller>@(varargin)obj.menu_file_load_single_callback(varargin{:})
Error in EC (line 7)
Error in front_end_menu_controller>@(x,y)EC(fcn) (line 263)

**Comment by seanwarren** [comment]
Hi, please could you send a copy of a file that isn't working for you to s.warren@garvan.org.au

**Comment by imunro** [comment]
Hi Sean. Does this mean that there are .sdt files that bio-formats can't handle ? If so I should let the bio-formats team know.

**Comment by seanwarren** [comment]
@imunro, I haven't recieved a file to test yet, if you are able to send a file over please do @pjmattei

**Comment by seanwarren** [comment]
@pjmattei, please could you test the following version which I believe resolves this issue:
https://storage.googleapis.com/flimfit-downloads/latest/5.1.1-22-gc63e3ac9/FLIMfit_5.1.1-22-gc63e3ac9_MACI64.zip

Would you be ok with us sharing this file with the OMERO team so they can look into the issue with bioformats?

**Comment by seanwarren** [comment]
@imunro - I have replaced the bioformats sdt reader with an implementation in FlimReader. This resolves this issue (which I believe is related to the size of the image - 256x2048x2048) and some other issues I've been having with multichannel and single-point sdt files not loading correctly using the bioformats reader. I'm open to switching back to bioformats at some point but this has become a blocking issue for a project at the moment.

**Comment by imunro** [comment]
@seanwarren if you could send me any examples of files which have shown issues then I can report them. Thanks.

**Comment by pjmattei** [comment]
@seanwarren please feel free to share.
There are still errors with this version :

 Invalid MEX-file '/Users/pj/Library/Application Support/.mcrCache9.1/FLIMfi1/Libraries/FlimReader.mexmaci64': dlopen(/Users/pj/Library/Application Support/.mcrCache9.1/FLIMfi1/Libraries/FlimReader.mexmaci64, 6): Library not loaded: @rpath/libmkl_rt.dylib
  Referenced from: /Users/pj/Library/Application Support/.mcrCache9.1/FLIMfi1/Libraries/FlimReader.mexmaci64                                                                                                                                                  
  Reason: image not found.                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                              
Error in flim_data_series/get_image_dimensions (line 206)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
Error in flim_data_series/load_multiple (line 30)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
Error in flim_data_series/load_single (line 104)                                                                                                                                                                                                              
                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                              
Error in flim_data_series_controller/load_single (line 168)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Error in front_end_menu_controller/menu_file_load_single_callback (line 656)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
Error in front_end_menu_controller>@(varargin)obj.menu_file_load_single_callback(varargin{:})                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
Error in EC (line 7)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
Error in front_end_menu_controller>@(x,y)EC(fcn) (line 263)

**Comment by seanwarren** [comment]
@pjmattei - apologies, I didn't have access to a mac to test last night. This version resolves that issue. 

https://storage.googleapis.com/flimfit-downloads/latest/5.1.1-24-ge5f33002/FLIMfit_5.1.1-24-ge5f33002_MACI64.zip

Let me know how you get on, cheers Sean
