### ISSUE TITLE
Error loading data from OMERO - can't find omeuiUtils

### ISSUE THREAD

**Issue by lucarav8** [flimfit/FLIMfit#353]
I installed FlimFIT for Windows, I insert the credentials for OMERO, everything seems ok.
When trying to load any type of file from OMERO I get this error:

Undefined variable "OMEuiUtils" or class "OMEuiUtils.OMEROImageChooser".                         
Error in front_end_menu_controller/menu_OMERO_Load_FLIM_Data_callback (line 390)                 
Error in front_end_menu_controller>@(varargin)obj.menu_OMERO_Load_FLIM_Data_callback(varargin{:})
Error in EC (line 7)                                                                             
Error in front_end_menu_controller>@(x,y)EC(fcn) (line 263)             

It looks to me that it cannot find the files that are in the repository "omeuiUtils".
Is that a bug or I missed something?

Luca

**Comment by seanwarren** [comment]
Luca, I'm afraid I don't have access to an OMERO server at the moment; please could you install v5.0.3 and let me know if you can access the server correctly with this version?

Also, which omero server version are you using?

Thanks,
Sean

**Comment by imunro** [comment]
Hi Luca  Sorry you're having issues. As Sean says, please let us know what OMERO version you are using 
and I think we can solve this.

Ian

**Comment by lucarav8** [comment]
Dear Sean and Ian,
Thanks for the prompt reply. 
I am using the OMERO demo server. I tried to find out on the website which version of the server it is but I couldn't. 
I tried with FLIMfit 5.0.3, however in this case I receive a message saying that it cannot connect to OMERO when I insert my credentials. Also, upon starting it, in the windows terminal I see the following messages:

Starting FLIMfit...

OMERO.matlab Toolbox
5.2.8-ice35-b57

Warning: Invalid file or directory 'C:\Users\Luca\AppData\Local\FLIMfit_5.0.3_PCWIN64_MCR_cache\mcrCache9.1\FLIMfi0\OMEROMatlab\libs\guava.jar'.
> In javaclasspath>local_validate_dynamic_path
  In javaclasspath>local_javapath
  In javaclasspath
  In javaaddpath (line 71)
  In loadOmero (line 73)
  In flim_fit_ui (line 164)
  In FLIMfit (line 39)
Warning: Invalid file or directory 'C:\Users\Luca\AppData\Local\FLIMfit_5.0.3_PCWIN64_MCR_cache\mcrCache9.1\FLIMfi0\OMEROMatlab\libs\omero_client.jar'.
> In javaclasspath>local_validate_dynamic_path
  In javaclasspath>local_javapath
  In javaclasspath
  In javaaddpath (line 71)
  In loadOmero (line 73)
  In flim_fit_ui (line 164)
  In FLIMfit (line 39)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Program%20Files/MATLAB/MATLAB%20Runtime/v91/java/jarext/slf4j/slf4j-log4j12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Luca/AppData/Local/FLIMfit_5.0.3_PCWIN64_MCR_cache/mcrCache9.1/FLIMfi0/BFMatlab/bioformats_package.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

**Comment by imunro** [comment]
Thanks Luca

I must apologise for this we haven't been keeping FLIMfit up-to-date with the very latest OMERO versions and , obviously, the demo server is kept at the cutting edge. Give me a couple of days , if you can, and I'll try and get an updated FLIMfit  that works with the demo server ready for you to test,

**Comment by lucarav8** [comment]
Thanks to you guys for your work.
I am testing FLIMfit since I am implementing a FLIM setup
and it looks to me a great job! Also thanks for the super fast 
assistance!
Luca

**Comment by imunro** [comment]
Hi Luca Could you possibly try this beta version 
https://storage.cloud.google.com/flimfit-downloads/latest/5.1.1-19-g8bc95a0b/FLIMfit%205.1.1-19-g8bc95a0b%20Setup%20x64.exe that should now work with the latest OMERO version.  Please note that  the FLIMfit UI is designed to have a similar 'look & feel' to the OMERO.insight desktop client although with obviously a much more limited functionality.

**Comment by lucarav8** [comment]
Hi Ian,
thanks a lot.
I tried and it works well!

Best,
Luca

**Comment by imunro** [comment]
Excellent, thanks Luca!

**Comment by lucarav8** [comment]
Thanks to you!

**Comment by imunro** [comment]
Fixed for OMERO v5.4.9 (probably for all 5.4)
