### ISSUE TITLE
Decay fit starting at wrong position from measured IRF (.sdt file) 

### ISSUE THREAD

**Issue by Isquare1** [flimfit/FLIMfit#368]
Hey, first of all thanks for a great software. I really enjoyed using it with a simulated IRF (which seemed to work pretty well, without any problems!) but now I acquired a 'real' IRF from my system, and unfortunately for some reason the decay fits always starts very off. First I thought the issue is the time resolution (the IRF I had was 1024 time bins, while the FIFO image was 256), however, I have the same problem with a 256-bin IRF as well. The IRF is a single .sdt measurement (not FIFO image). 

![flimfiterror1](https://user-images.githubusercontent.com/52381942/99313703-eab61780-2857-11eb-973e-0e3e7eaa29b5.PNG)

![flimfiterror2](https://user-images.githubusercontent.com/52381942/99313708-ee499e80-2857-11eb-9f15-d334b9077c73.PNG)

PS.:  I tried to see where the issue might be by finding the part of the code that deals with the decay fitting but I couldn't find it. Maybe just a reference to this part of the code will also be useful.

**Comment by seanwarren** [comment]
Hello, looks like the repetition rate is set incorrectly. FLIMfit defaults to 80MHz if it can’t read it from the data, but it looks like your laser is more like 20MHz
